pipeline:
  # build:
  #   image: node:8.11.3-alpine
  #   secrets: [FACEPP_KEY, FACEPP_SECRET]
  #   commands:
  #     - npm install
      # - npm test
  ssh-deploy:
    image: appleboy/drone-ssh
    pull: true # always pull the latest version of the `drone-ssh` plugin
    secrets: [ssh_username, ssh_key]
    host: 172.17.0.1
    port: 22
    command_timeout: 2m
    script:
      - bash ~/git/star_line_bot_backend/script/deploy.sh
    when:
      event: [push, tag, deployment]