version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ${PWD}:/app
    command:
      - npm 
      - start 
  db:
    image: mysql:5.7.24
    ports: 
      - 3306:3306
    environment:
        MYSQL_PASSWORD: root 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
