version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ${PWD}:/app
    working_dir: /app
    networks:
      - default
    command:
      - npm 
      - start 
  serveo:
    image: node:latest 
    volumes: 
      - ${PWD}:/app
    working_dir: /app
    command:
      - bash
      - script/serveo.sh
    networks:
      - default
  db:
    image: mysql:5.7.24
    ports: 
      - 3306:3306
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
