version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    working_dir: /app
    user: ${CURRENT_UID}
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - mysql
    command:
      - npm
      - run
      - dev

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./other/mongo:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  mysql:
    image: mysql:5.7
    volumes:
      - ./other/mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodocker
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
