version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 5500:5000
      - 8080:8080
    tty: true
    volumes:
      - ${PWD}:/app
    working_dir: /app
    networks: 
      - default
    command:
      - npm 
      - start 