version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
      - 8080:8080
    tty: true
    volumes:
      - ${PWD}:/app
    working_dir: /app
    networks: 
      - default
    command:
      - npm 
      - start 
  serveo:
    image: node:latest 
    volumes: 
      - ${PWD}:/app
    working_dir: /app
    networks: 
      - default
    command:
      - bash
      - script/serveo.sh
  db:
    image: mysql:5.7.24
    ports: 
      - 3306:3306
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
    networks: 
      - default
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
  swagger-ui:
      image: swaggerapi/swagger-ui
      ports:
        - 8070:8080
      volumes:
        - ${PWD}/swagger:/swagger
      environment:
        SWAGGER_JSON: /swagger/openapi.yaml
  swagger-editor:
      image: swaggerapi/swagger-editor
      ports:
        - 8090:8080