version: "3"
services:
  app:
    image: node:10.16
    volumes:
      - ./:/app
    env_file:
      - .env
    working_dir: /app
    user: ${CURRENT_UID}
    ports:
      - 8080:8080
    depends_on:
      - mongo
    command:
      - npm
      - run
      - dev

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db