openapi: 3.0.1
info:
  title: 髒沙發APIs
  description: '為了紳士幸福的平台'
  version: 1.0.0
servers:
  - url: 'http://192.168.99.1:5000'
tags:
  - name: 'Face++'
paths:
  /test:
    post:
      tags:
        - default
      requestBody:
        description: 上傳圖片進行搜索
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
  /facepp/faceSet/search:
    post:
      tags:
        - Face++
      summary: 針對一個FaceSet進行搜索
      requestBody:
        description: 上傳圖片進行搜索
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                token:
                  type: string
                  default: 9372686ee50665315878a0ecd0f82916
        required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search'
  /facepp/faceSet/list:
    get:
      tags:
        - Face++
      summary: 取得所有FaceSet id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    search:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold